---
- hosts: localhost
  become: true
  tasks:
  - name: updates
    apt:
      name: {{item}}
      state: latest
      update_cache: yes
    with_items:
       - nginx
       - php5-common
       - php5-cli
       - php5-fpm
